services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - render.yaml
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d028stuuk2gs73e7lbc0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: fichas_clinicas
      - key: DB_USERNAME
        value: admin
      - key: DB_PASSWORD
        value: WlUKLYh20F3twMbrIRwR9cFj8eo5XnkN
